name: nyc_airbnb_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - hydra-core=1.3.2
  - matplotlib=3.8.2
  - pandas=2.1.3
  # - jupyterlab=4.0.9
  - pip=23.3.1

  - ipython=8.22.2
  # - notebook=7.1.3
  - jupyterlab=4.0.9
  - cookiecutter=2.6.0
  # - cookiecutter=1.7.2
  - pip:
      - mlflow==2.8.1
      - wandb==0.16.0

# name: nyc_airbnb_dev
# channels:
#   - conda-forge
#   - defaults
# dependencies:
#   - mlflow=1.14.1
#   - ipython=7.21.0
#   - notebook=6.2.0
#   - jupyterlab=3.0.10
#   - cookiecutter=1.7.2
#   - hydra-core=1.0.6
#   - matplotlib=3.3.4
#   - pandas=1.2.3
#   - git=2.30.2
#   - pip=20.3.3
#   - pip:
#       - wandb==0.10.31
